---
abstract: 'framework for more readable interactive test scripts'
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Inter
provides:
  Test::Inter:
    file: lib/Test/Inter.pm
    version: 1.01
requires:
  File::Basename: 0
  IO::File: 0
  perl: 5.004
resources:
  license: http://dev.perl.org/licenses/
version: 1.01
